### PR TITLE
HANDLE LARGE INTEGERS WITH CARE

### PR DESCRIPTION
**Pull request by mjmcnelis**
I believe the seg fault was due to the long long integers that appear in the code. 

e.g. long long int X = npart * FO_chunk * pT_tab_length * phi_tab_length * y_tab_length
has a bug because the r.h.s. is integers x integers arithmetic which when too large gives you nonsense.

Look at the changes I made. This should be done elsewhere, like in the GPU version

### CODE REVIEW

**Review by derekeverett — COMMENTED** [review]
AH this makes sense. Did you try running it and did the seg fault go away?

**Comment by mjmcnelis** [comment]
I ran it and it seemed to go away. I couldn’t tell if it would finish bc the cpu is so slow. Why didn’t this problem show up before, i thought you ran it once w/ 300 resonances

**Comment by derekeverett** [comment]
I think I didnt notice it before because we were using a smaller f0 surface with like 30K elements before. this new one has like 100K elements

**Comment by mjmcnelis** [comment]
I don’t think that was the reason. The dN_pTdpTdphidy_all depended on FO_chunk which was fixed to 10000

**Pull request merged**
